# Generated by Django 4.2.13 on 2024-07-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/account/defolt_avatar.png', null=True, upload_to='media/', verbose_name='Аватар'),
        ),
    ]
