# Generated by Django 4.2.13 on 2024-07-02 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/images/tournaments/', verbose_name='Изображение')),
                ('organizer', models.CharField(blank=True, max_length=150, null=True, verbose_name='Организатор')),
                ('tournament_start_date', models.DateTimeField(verbose_name='Дата начала турнира')),
                ('tournament_end_date', models.DateTimeField(verbose_name='Дата окончания турнира')),
                ('registration_start_date', models.DateTimeField(verbose_name='Дата начала регистрации')),
                ('registration_end_date', models.DateTimeField(verbose_name='Дата окончания регистрации')),
                ('status', models.CharField(choices=[('Active', 'Предстоящий'), ('Archive', 'Завершенный')], max_length=150, verbose_name='Статус')),
                ('format_of_tournament', models.CharField(choices=[('Single Elimination', 'Олимпийская система'), ('Double Elimination', 'Выбывание после 2-х поражений'), ('Round Robbin', 'Круговая система')], max_length=150, verbose_name='Формат')),
                ('type_of_tournament', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=150, verbose_name='Тип')),
                ('format_of_participation', models.CharField(choices=[('1', '1X1'), ('2', '2X2'), ('5', '5X5')], max_length=150, verbose_name='Формат участия')),
                ('prize_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Призовой фонд')),
                ('game', models.CharField(choices=[('Dota 2', 'Dota 2'), ('CS2', 'Counter Strike 2'), ('HS', 'Hearthstone Battlegrounds'), ('Valorant', 'Valorant')], max_length=150, verbose_name='Игра')),
                ('max_teams', models.PositiveIntegerField(default=64, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество команд')),
                ('registered_teams', models.ManyToManyField(blank=True, related_name='tournaments', to='teams.team')),
            ],
        ),
    ]
