# Generated by Django 5.0.6 on 2024-07-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/tournaments/', verbose_name='Изображение'),
        ),
    ]
