# Generated by Django 4.2.13 on 2024-07-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/account/defolt_avatar.png', null=True, upload_to=''),
        ),
    ]
